version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pr_review_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: pr_review_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/pr_service?sslmode=disable"
      PORT: 8080
    ports:
      - "8080:8080"

volumes:
  pgdata:
